### ISSUE TITLE
Upgraded Clojure to 1.8 and now I see this java.lang.NoClassDefFoundError for HeaderMap

### ISSUE THREAD

**Issue by JMacLulich** [dakrone/clj-http#335]
Hi Guys,

I'm trying to figure out what the has caused this error to appear in my project after bumping up the version of Clojure from 1.7 to 1.8 in my project.

I now get this error whenever I try and require the `clj-http`

`Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap`

I think its got something to do with interactions with `clj-oauth` or some other OAuth library I'm using that is importing an older version of `clj-http`. `clj-oauth` for instance includes `clj-http` `v2.0.2`.

Has anyone seen this error before when updating their version of Clojure?

Thanks, Jason.

**Comment by JMacLulich** [comment]
Just to expand on the error above, I get this:

```
1. Caused by java.lang.NoClassDefFoundError
   IllegalName:
   compile__stub.clj_http.headers.clj-http.headers/HeaderMap
```

**Comment by dakrone** [comment]
Sounds like it might be something that causing bad dependencies? What does `lein dependencies :tree` spit out?

**Comment by s4s0l** [comment]
Same for me, using gradle not lein but effect as described above:
```
+--- org.clojure:clojure:1.8.0
\--- clj-http:clj-http:2.3.0
     +--- org.apache.httpcomponents:httpcore:4.4.5
     +--- org.apache.httpcomponents:httpclient:4.5.2
     |    +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.5
     |    +--- commons-logging:commons-logging:1.2
     |    \--- commons-codec:commons-codec:1.9 -> 1.10
     +--- org.apache.httpcomponents:httpmime:4.5.2
     |    \--- org.apache.httpcomponents:httpclient:4.5.2 (*)
     +--- commons-codec:commons-codec:1.10
     +--- commons-io:commons-io:2.5
     +--- slingshot:slingshot:0.12.2
     \--- potemkin:potemkin:0.4.3
          +--- clj-tuple:clj-tuple:0.2.2
          \--- riddley:riddley:0.1.12
```

**Comment by jiacai2050** [comment]
3.9.0 still have this issue

```
Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
	at clojure.lang.Compiler$NewInstanceExpr.compileStub(Compiler.java:7903)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7768)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7678)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
```

**Comment by jiacai2050** [comment]
After digging into this issue, I have found the root cause:

- https://dev.clojure.org/jira/browse/CLJ-1208

Briefly speaking, clojure 1.8's change affect potemkin, and is already fix in https://github.com/ztellman/potemkin/pull/40.
clj-http(3.9.0) depends on potemkin 0.4.5, which contains the fix, but if your dependencies contains older version of potemkin, then you will problabley see this issue.

I'm not sure which is the earliest version contains the fix, but 0.4.5 surely do.

**Comment by JMacLulich** [comment]
Thanks for the update guys, I have to admit i did loose track of this ticket after filing it, but appreciate the continued updates over the years.

**Comment by jiacai2050** [comment]
@JMacLulich Close now?

**Comment by dakrone** [comment]
Sounds like this is resolved, so I'm going to close this for now
